api_platform:
    title: Symfony API Platform
    version: 1.0.0
    show_webby: false
    formats:
        json:
            mime_types: ['application/json']
        xml:
            mime_types: ['text/xml']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
